version: "3.7"
services:
  catalog_api:
    container_name: catalog_api
    build:
      context: .
      dockerfile: containers/api/Dockerfile
    env_file:
      - containers/api/api.env
    volumes:
         - ./certificates/:/https
    networks:
      - my_network
    ports:
      - 5000:5000
      - 5001:5001
    depends_on:
      - catalog_db
      - catalog_esb
      
  catalog_db:
    container_name: catalog_db
    image: microsoft/mssql-server-linux
    networks:
      - my_network
    env_file:
      - containers/db/db.env
  
  catalog_esb:
    container_name: catalog_esb
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - my_network
  
networks:
  my_network:
    driver: bridge